/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.student_app;

import java.awt.Color;

/**
 *
 * @author Admin
 */
public class About extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(About.class.getName());

    /**
     * Creates new form About
     */
    public About() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        show = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTextArea();
        show1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        show2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        show3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        show4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        jLabel6.setBackground(new java.awt.Color(255, 204, 51));
        jLabel6.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 255));
        jLabel6.setText("Your welcome To Fees Management System ");
        jLabel6.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        jLabel7.setBackground(new java.awt.Color(255, 204, 51));
        jLabel7.setFont(new java.awt.Font("Rockwell", 2, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("Creted By Jadhav Pavan Techno");
        jLabel7.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(617, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        show.setBackground(new java.awt.Color(204, 255, 0));
        show.setBorder(new javax.swing.border.MatteBorder(null));
        show.setForeground(new java.awt.Color(255, 204, 204));
        show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Show");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout showLayout = new javax.swing.GroupLayout(show);
        show.setLayout(showLayout);
        showLayout.setHorizontalGroup(
            showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
            .addGroup(showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showLayout.createSequentialGroup()
                    .addContainerGap(17, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)))
        );
        showLayout.setVerticalGroup(
            showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(showLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showLayout.createSequentialGroup()
                    .addContainerGap(13, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );

        t1.setColumns(20);
        t1.setRows(5);
        jScrollPane1.setViewportView(t1);

        show1.setBackground(new java.awt.Color(204, 255, 0));
        show1.setBorder(new javax.swing.border.MatteBorder(null));
        show1.setForeground(new java.awt.Color(255, 204, 204));
        show1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Clear");
        jLabel2.setOpaque(true);

        javax.swing.GroupLayout show1Layout = new javax.swing.GroupLayout(show1);
        show1.setLayout(show1Layout);
        show1Layout.setHorizontalGroup(
            show1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
            .addGroup(show1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, show1Layout.createSequentialGroup()
                    .addContainerGap(17, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)))
        );
        show1Layout.setVerticalGroup(
            show1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(show1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(show1Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jLabel2)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );

        show2.setBackground(new java.awt.Color(204, 255, 0));
        show2.setBorder(new javax.swing.border.MatteBorder(null));
        show2.setForeground(new java.awt.Color(255, 204, 204));
        show2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                show2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                show2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                show2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                show2MouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Back");
        jLabel3.setOpaque(true);

        javax.swing.GroupLayout show2Layout = new javax.swing.GroupLayout(show2);
        show2.setLayout(show2Layout);
        show2Layout.setHorizontalGroup(
            show2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(show2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        show2Layout.setVerticalGroup(
            show2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(show2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        show3.setBackground(new java.awt.Color(204, 255, 0));
        show3.setBorder(new javax.swing.border.MatteBorder(null));
        show3.setForeground(new java.awt.Color(255, 204, 204));
        show3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                show3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                show3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                show3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                show3MouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Change");
        jLabel4.setOpaque(true);

        javax.swing.GroupLayout show3Layout = new javax.swing.GroupLayout(show3);
        show3.setLayout(show3Layout);
        show3Layout.setHorizontalGroup(
            show3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
            .addGroup(show3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(show3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addGap(18, 18, 18)))
        );
        show3Layout.setVerticalGroup(
            show3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(show3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, show3Layout.createSequentialGroup()
                    .addContainerGap(13, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );

        show4.setBackground(new java.awt.Color(204, 255, 0));
        show4.setBorder(new javax.swing.border.MatteBorder(null));
        show4.setForeground(new java.awt.Color(255, 204, 204));
        show4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("course");
        jLabel5.setOpaque(true);

        javax.swing.GroupLayout show4Layout = new javax.swing.GroupLayout(show4);
        show4.setLayout(show4Layout);
        show4Layout.setHorizontalGroup(
            show4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
            .addGroup(show4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, show4Layout.createSequentialGroup()
                    .addContainerGap(17, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)))
        );
        show4Layout.setVerticalGroup(
            show4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(show4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, show4Layout.createSequentialGroup()
                    .addContainerGap(13, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(show2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(show1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(show3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(show4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(show2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        t1.setText("""
                              ABOUT OUR COURSES FOLLOWING SOME RULES FOR YOU...
                   payment process simple and organized for everyone.
                   
                   1.   Fee Reminder for School
                   "Dear Parents, this is a reminder that the school fee for [Student\u2019s Name] 
                   is due on [Due Date]. Please ensure payment is made on time to avoid late fees.
                    Thank you!"
                   2.   College Fee Due Reminder
                   "Dear Parents, the college fee for [Student\u2019s Name] is due by [Due Date].
                    Kindly make the payment as soon as possible. Thank you!"
                   3.   Upcoming Fee Reminder
                   "Dear Parents, this is a reminder that the next fee payment for [Student\u2019s Name]
                    is due on [Due Date]. Please make the payment on time to 
                    ensure your child's enrollment continues."
                   4.   Early Fee Payment Reminder
                   "Dear [Parent\u2019s Name], we noticed that the payment for [Student\u2019s Name] is due.
                   Please pay before [Due Date] to avoid any late fees."
                   5.  Last Payment Reminder
                   "Dear [Parent\u2019s Name], this is the final reminder for [Student\u2019s Name]'s school fee.
                    Please pay before [Due Date] to avoid disruption in your child\u2019s classes."
                   6.   Payment Options Reminder
                   "Dear [Parent\u2019s Name], your fee payment for [Student\u2019s Name] is due soon.
                    You can pay via [Payment Options]. Please ensure the payment is made by [Due Date]."
                   7.   Friendly Fee Reminder
                   "Dear [Parent\u2019s Name], we noticed that the payment for [Student\u2019s Name] is still
                    pending. Kindly make the payment by [Due Date]. Thank you for your prompt action!"
                   8.   Early Bird Discount Reminder
                   "Dear [Parent\u2019s Name], pay the school fees for [Student\u2019s Name] before
                    [Early Bird Date] to avail of discounts. Don\u2019t miss out on this benefit!"
                   9.   Fee Deadline Reminder
                   "Dear [Parent\u2019s Name], a reminder that the fee payment for [Student\u2019s Name] 
                    is due on [Due Date]. Please make sure to pay before the deadline to avoid any inconvenience."
                   10.   Fee Payment Alert
                   "Dear [Parent\u2019s Name], the fee for [Student\u2019s Name] is due on [Due Date].
                    Please make sure to pay on time to avoid late payment charges."
                   11.  Thank You for Payment
                   "Dear [Parent\u2019s Name], thank you for your prompt
                    payment for [Student\u2019s Name]. We appreciate your cooperation!"
                   12.  Payment Confirmation
                   "Dear [Parent\u2019s Name], we have received your payment
                    for [Student\u2019s Name]. Thank you for your quick response!"
                   13.  Payment Plan Reminder
                   "Dear Parents, a reminder that the next installment of 
                   the fee for [Student\u2019s Name] is due on [Due Date].
                    Please refer to your payment plan for more details."
                   14.  Fee Reminder for New Term
                   "Dear [Parent\u2019s Name], the fee for [Student\u2019s Name] for the new
                    term is due soon. Please make the payment by [Due Date]."
                   15.  Reminder for Pending Fee Payment
                   "Dear [Parent\u2019s Name], we noticed that [Student\u2019s Name]\u2019s fee 
                   payment is still due. Please make the payment to avoid any disruption in classes."
                   16.  Important Fee Information
                   "Dear [Parent\u2019s Name], please be advised that the fee for 
                   [Student\u2019s Name] is due on [Due Date]. Kindly ensure timely payment to avoid disruptions."
                   17.  Late Fee Warning
                   "Dear Parents, the fee for [Student\u2019s Name] is due soon. A late
                    fee will be charged if payment is made after [Late Fee Date]. Please make the payment by [Due Date] to avoid additional charges."
                   18.  Gentle Reminder for Fee Payment
                   "Dear Parents, this is a friendly reminder that the fee for [Student\u2019s Name] 
                   is due on [Due Date]. Kindly make the payment as soon as possible."
                   19.  Fee for New Semester Reminder
                   "Dear Parents, the fee for the new semester for [Student\u2019s Name] is due by 
                   [Due Date]. Please make the payment on time."
                   20.  Fee Reminder with Contact Information
                   "Dear [Parent\u2019s Name], the fee for [Student\u2019s Name] is due soon. If you have 
                   any questions, please contact us at [Contact Information]."
                   21.  Legal Considerations & Parent Engagement with Fees Due Messages
                   When sending fees due messages, schools and colleges need to consider certain
                    legal rules to follow privacy laws. Different countries have laws to protect personal information, like the General Data Protection Regulation (GDPR) in Europe and similar laws in India, such as the Information Technology Act, 2000. Schools must ensure that parents\u2019 and students\u2019 personal details are kept safe and that messages are sent only to the right people. It\u2019s also important to make sure the message is not too harsh or threatening, as that could cause legal problems. Schools must get clear permission from parents to send these reminders via SMS, email, or WhatsApp.
                   
                   Besides legal concerns, sending respectful and timely reminders for fees can
                    improve how parents engage with the school. When parents get reminders about payments or deadlines on time, they are more likely to pay on time, which helps avoid late fees. These messages also help keep clear communication between the school and parents, making sure they both understand the fee situation. With options like SMS, email, and WhatsApp, schools can meet parents\u2019 needs and make payment handling easier. This approach helps build trust, transparency, and a stronger relationship between parents and the school for the long term.
                   
                   22.   Last Words
                   Sending clear and timely fees due messages is important for keeping strong 
                   communication between parents and schools. As a trusted bulk SMS service provider, Shree Tripada allows schools, colleges, and other educational institutions to easily send important messages like fee reminders and attendance updates. These bulk SMS services help schools build better relationships with parents, ensuring smooth communication and quick responses. Many schools and colleges have used Shree Tripada\u2019s bulk SMS service to improve their communication and make their operations more efficient.
                   
                   Try For joint to our courses...  
                   
                                  !!......YOUR  WELCOME......!!""");        // TODO add your handling code here:
    }//GEN-LAST:event_showMouseClicked

    private void show1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show1MouseClicked
        t1.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_show1MouseClicked

    private void show2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show2MouseClicked
        this.setVisible(false);
        new Homepage().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_show2MouseClicked

    private void show3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show3MouseClicked
        t1.setBackground(Color.red);        // TODO add your handling code here:
    }//GEN-LAST:event_show3MouseClicked

    private void show4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show4MouseClicked
        this.setVisible(false);
        new feesOfCoursess().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_show4MouseClicked

    private void show2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show2MouseEntered
        t1.setBackground(Color.yellow);
        t1.setForeground(Color.green);// TODO add your handling code here:
    }//GEN-LAST:event_show2MouseEntered

    private void show2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show2MouseExited
        t1.setBackground(Color.red);
        t1.setForeground(Color.blue);        // TODO add your handling code here:
    }//GEN-LAST:event_show2MouseExited

    private void show2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show2MouseReleased
        t1.setBackground(Color.white);
        t1.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_show2MouseReleased

    private void show2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show2MousePressed
        t1.setBackground(Color.ORANGE);
        t1.setForeground(Color.darkGray);        // TODO add your handling code here:
    }//GEN-LAST:event_show2MousePressed

    private void show3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show3MouseEntered
        t1.setBackground(Color.gray);        // TODO add your handling code here:
    }//GEN-LAST:event_show3MouseEntered

    private void show3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show3MouseExited
        t1.setBackground(Color.green);        // TODO add your handling code here:
    }//GEN-LAST:event_show3MouseExited

    private void show3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show3MousePressed
        t1.setBackground(Color.yellow);        // TODO add your handling code here:
    }//GEN-LAST:event_show3MousePressed

    private void show3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show3MouseReleased
        t1.setBackground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_show3MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new About().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel show;
    private javax.swing.JPanel show1;
    private javax.swing.JPanel show2;
    private javax.swing.JPanel show3;
    private javax.swing.JPanel show4;
    private javax.swing.JTextArea t1;
    // End of variables declaration//GEN-END:variables
}
