/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.student_app;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class category extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(category.class.getName());

    /**
     * Creates new form category
     */
    public category() {
        initComponents();
        idstd.setVisible(false);
        jLabel5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        scroll = new javax.swing.JScrollPane();
        p1 = new javax.swing.JTextPane();
        jToolBar1 = new javax.swing.JToolBar();
        catg = new javax.swing.JComboBox<>();
        username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        catglbl1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        perctg = new javax.swing.JLabel();
        catglbl2 = new javax.swing.JLabel();
        pass1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        idstd = new javax.swing.JTextField();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        setForeground(new java.awt.Color(255, 0, 51));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Welcome Student For Category Wise Off");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("Clear ");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 102));
        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setText("Go Back");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 102));
        jButton3.setForeground(new java.awt.Color(0, 0, 204));
        jButton3.setText("View Details");
        jButton3.setBorder(new javax.swing.border.MatteBorder(null));
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        p1.setBackground(new java.awt.Color(255, 255, 204));
        p1.setForeground(new java.awt.Color(0, 0, 255));
        scroll.setViewportView(p1);

        jToolBar1.setRollover(true);

        catg.setBackground(new java.awt.Color(51, 255, 0));
        catg.setFont(new java.awt.Font("Rockwell Condensed", 0, 14)); // NOI18N
        catg.setForeground(new java.awt.Color(255, 0, 153));
        catg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Category  :", "SC ", "ST ", "NT ", "VJ(DT)A", "VJ(DT)B", "OBC", "EWS", "OPEN" }));
        catg.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        catg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catgActionPerformed(evt);
            }
        });

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Enter Username :");

        jLabel4.setFont(new java.awt.Font("Script MT Bold", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 255));
        jLabel4.setText("Created By Jadhav Pavan Techno .");

        catglbl1.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        catglbl1.setForeground(new java.awt.Color(255, 0, 255));

        jButton4.setBackground(new java.awt.Color(255, 255, 102));
        jButton4.setForeground(new java.awt.Color(0, 0, 204));
        jButton4.setText("discount");
        jButton4.setBorder(new javax.swing.border.MatteBorder(null));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("Id :");

        perctg.setFont(new java.awt.Font("Vivaldi", 1, 18)); // NOI18N
        perctg.setForeground(new java.awt.Color(51, 0, 255));

        catglbl2.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        catglbl2.setForeground(new java.awt.Color(0, 0, 255));

        jLabel6.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("Enter Password:");

        idstd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idstdActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(255, 255, 102));
        delete.setForeground(new java.awt.Color(0, 0, 204));
        delete.setText("Delete");
        delete.setBorder(new javax.swing.border.MatteBorder(null));
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(idstd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(perctg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(catg, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(catglbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(catglbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pass1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idstd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(perctg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(catg, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(catglbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(catglbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        p1.setVisible(true);
        p1.setText("               HOW TO MAKE DISCOUNT RELATES CATEGORIAL STUDENTS ...\n\n" + "To inform students about category-wise fee concessions,\n educational institutions should create official documents \n(like a fee structure PDF) detailing benefits based on income,\n social category (SC, ST,NT, OBC, EWS), or other factors, making sure \nthe information is easily accessible on the institute's \nofficial website and clearly outlines eligibility criteria and the \napplication process for any applicable waivers or \nscholarships. \n"
                + "1. Develop a Clear Fee Structure:\n"
                + "Categorize Fees:\n"
                + "Create a comprehensive fee structure that\n clearly lists different fee components, such as\n tuition, hostel, and exam fees. \n"
                + "Define Categories:\n"
                + "Specify the categories eligible for fee\n concessions, which often include  SC , ST , NT , vJ , NTC , OBC, EWS, \nand sometimes PwD, as well as income-based categories.\n"
                + "2. Determine Fee Waivers and Concessions:\n"
                + "Institutional Policy:\n"
                + "Refer to the institute's internal policies, government regulations, \nand national initiatives (like those for IITs)\n that mandate fee structures and concessions for \ndifferent categories. \n"
                + "Income-Based Waivers:\n"
                + "Implement waivers based on parental income,\n such as full waivers for very low incomes and\n partial waivers for middle-income groups. \n"
                + "3. Publish Fee Information: \n"
                + "Official Website:\n"
                + "Publish the detailed fee structure\n on the institute's official website \n in an easily accessible format, like a PDF document.\n"
                + "Admissions Portal:\n"
                + "Include fee-related information in the\n student's academic portal or\n at the point of online fee payment.\n"
                + "4. Provide Application Guidelines (If Applicable): \n"
                + "Apply for Concessions:\n"
                + "If students need to apply for a waiver or scholarship,\n provide clear instructions and a dedicated portal or application form.\n"
                + "Support Documents:\n"
                + "List all required supporting documents, \nsuch as income certificates or category certificates,\n to be submitted with the application.\n"
                + "5. Ensure Clear Communication:\n"
                + "Notifications:\n"
                + "Issue notifications regarding the fee structure\n and any changes through official communication channels,\n such as emails or announcements on the institute's portal. \n"
                + "Information for Students:\n"
                + "Make sure the information is easily understandable by\n all students and their parents by using clear language. \n" + "\n    how to off about fees to students category wise\n"
                + "Category-wise fee exemptions and waivers for students\n"
                + "Various institutions and government bodies\n offer fee exemptions and waivers to students based on\n different categories, primarily aiming to support those \nfacing financial hardship or belonging to specific \ngroups. \n"
                + "1. Kendriya Vidyalaya Sangathan (KVS) - specific exemptions\n"
                + "Girls Students (Classes 1-12): Exempted from tuition fees.\n"
                + "SC/ST Students: Exempted from tuition fees.\n"
                + "Children of KVS Employees: Exempted from tuition fees.\n"
                + "Children of Armed Forces Personnel:\n Children of those killed or disabled in various conflicts \n(1962, 1965, 1971, 1999) and operations like \n\"Operation Meghdoot\" and \"Operation Vijay\" are \nexempt from both tuition fees and Vidyalaya Vikas Nidhi (VVN). \nSimilar exemptions are also extended to children of Armed\n Forces/Paramilitary Forces personnel killed/declared missing or \npermanently disabled during counter-insurgency operations\n in India or abroad.\n"
                + "Children from Below Poverty Line (BPL) Families \n(up to two children): Exempted from tuition fees,\n VVN, and Computer Fund.\n"
                + "Disabled Students:\n Exempted from tuition fees, VVN, and Computer Fund,\n subject to specific conditions mentioned in KVS\n letter dated 15.10.2009.\n"
                + "Single Girl Child (Classes 6-12):\n Girls who are the only child of their parents are exempt\n from tuition fees and VVN. \n"
                + "2. Higher education - general fee waiver and scholarship schemes\n"
                + "Need-Based Fee Waivers: \nMany universities, including those abroad, offer \nneed-based fee waivers for students who demonstrate \nfinancial need. This often involves submitting \nfinancial documents like income statements or tax returns. Students \nfacing financial hardships due to job loss, personal \ndisruptions, being an orphan/ward of the state, or residing\n in low-income areas might qualify.\n"
                + "Merit-Based Scholarships:\n These are awarded to students with excellent academic\n records or specific achievements like those in sports \nor community service.\n"
                + "AICTE Tuition Fee Waiver Scheme: \nThis scheme provides a full waiver of tuition fees\n for economically disadvantaged students pursuing \ntechnical education in India. Eligibility is \nbased on the annual family income not exceeding \nRs. 8 lakh and admission through merit in respective entrance \nexams, according to Sarsa Education.\n"
                + "Central Sector Scheme of Scholarship for College and University Students:\n This scholarship provides financial assistance to meritorious \nstudents from low-income families based on Class 12th Board Examination \nresults, says myScheme.\n"
                + "National Overseas Scholarship (NOS) for SC etc.\n Candidates: Provides financial support for students \nbelonging to SC and other categories to pursue higher education \nabroad.\n"
                + "PM-USP Special Scholarship Scheme for Jammu & Kashmir & Ladakh:\n This scheme encourages youth from Jammu & Kashmir and Ladakh \nto pursue education outside the state by offering scholarships \nthat cover tuition fees and maintenance allowances. Eligibility includes \npassing class 12 or diploma from the region and securing \nadmission in recognized institutions, according to Education.\nGov.in.\n"
                + "Scholarships for Women:\n Many scholarships are specifically designed for female students\n to encourage gender equality in education. Examples include\n the Pragati Scholarship for Girls for technical degrees \nand the K.C. Mahindra Scholarship for women seeking higher \neducation abroad. \n"
                + "3. Applying for fee waivers and scholarships\n"
                + "Research Eligibility Criteria: \nIdentify institutions and programs offering fee waivers and\n thoroughly review their eligibility requirements, including inc\nome thresholds or academic achievements.\n"
                + "Prepare Necessary Documentation:\n This may include financial statements, tax returns, standardized\n test scores, academic transcripts, or income certificates.\n"
                + "Reach Out to Admissions Offices:\n Contact the admissions office of your\n target institutions to inquire about \nfee waiver possibilities and explain your situation.\n"
                + "Explore External Scholarship Programs:\n Look for scholarships offered by government agencies, \nnon-profit organizations, and private companies that\n align with your background and academic goals.\n"
                + "Apply Early and Often:\n Begin the application process early for both \ninstitutional and external scholarships to maximize your \nchances of securing financial aid, recommends Forbes.\n"
                + "Submit a Formal Appeal Letter:\n If you have received a better offer from another institution\n or experienced a change in family circumstances \n(e.g., job loss, medical expenses), you can submit a formal appeal\n letter to the financial aid office to negotiate for additional\n aid. \n"
                + "Note: \nEligibility criteria and application procedures \ncan vary between institutions and programs. It's \ncrucial to research each opportunity thoroughly and \ncontact the relevant authorities for clarification. " + "\n\n    Your Wecome My Dear Students To,Our Technical Collage");// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        p1.setVisible(false);        // TODO add your handling code here:
        catglbl1.setText("");
        perctg.setText("");
        username.setText("");
        pass1.setText("");
        catglbl2.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new Homepage().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    void category1() {
        if (catg.getSelectedIndex() == 0) {
            catglbl1.setText("");
            catglbl2.setText("");

        }
        if (catg.getSelectedIndex() == 1) {
            catglbl1.setText(" 40.0");
            catglbl2.setText("SC");
            //3400*40/100=1360
        }
        if (catg.getSelectedIndex() == 2) {
            catglbl1.setText(" 40.0");
            catglbl2.setText("ST");
        }
        if (catg.getSelectedIndex() == 3) {
            catglbl1.setText(" 17.0");
            catglbl2.setText("NT");
        }
        if (catg.getSelectedIndex() == 4) {
            catglbl1.setText("15.0");
            catglbl2.setText("VJ(DT)A");
        }
        if (catg.getSelectedIndex() == 5) {
            catglbl1.setText(" 15.0");
            catglbl2.setText("VJ(DT)B");
        }
        if (catg.getSelectedIndex() == 6) {
            catglbl1.setText(" 5.0");
            catglbl2.setText("OBC");
        }
        if (catg.getSelectedIndex() == 7) {
            catglbl1.setText(" 7.0");
            catglbl2.setText("EWS");
        }
        if (catg.getSelectedIndex() == 8) {
            catglbl1.setText(" 3.0");
            catglbl2.setText("OPEN");
        }
    }
    String amount, cat, uname, pass, disc1, category;
    Double amt, cast;
    int id = 1;

    int idEnterKarPavan() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");                   // totelamount
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentapp", "root", "pavan@1234");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT max(id) from discount");
            while (rs.next()) {

                id = rs.getInt(1);
                id++;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        return id;
    }

    void insertData() {
        category = catglbl2.getText();
        cat = catglbl1.getText();
        uname = username.getText();
        pass = pass1.getText();
        amt = Double.valueOf(amount);//3400
        cast = Double.valueOf(cat);//40.0
        amt = (amt * cast / 100);         //perctg
        String s1 = (String) amt.toString();
        perctg.setText(s1);
        try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentapp", "root", "pavan@1234")) {
            disc1 = perctg.getText();
            if (disc1 == null) {
                JOptionPane.showMessageDialog(this, "Please , Insert data ....");
            }

            PreparedStatement ps = con.prepareStatement("insert into discount values(?,?,?,?,?,?)");
            ps.setInt(1, idEnterKarPavan());
            ps.setString(2, uname);//username
            ps.setString(3, pass);//course
            ps.setString(4, cat);//totelamount
            ps.setString(5, disc1);//Discount>>
            ps.setString(6, category);

            int s = ps.executeUpdate();
            {
                if (s > 0) {
                    JOptionPane.showMessageDialog(this, "Record Inserted Successfully....");

                } else {
                    JOptionPane.showMessageDialog(this, "Record Not Inserted ....");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    boolean validation() {
        cat = catglbl1.getText();
        uname = username.getText();
        pass = pass1.getText();
        if (uname.equals("")) {
            JOptionPane.showMessageDialog(this, "Plz , Enter Username....");
            return false;
        }
        if (pass.equals("")) {
            JOptionPane.showMessageDialog(this, "Plz , Enter Password....");
            return false;
        }
        if (cat.equals("")) {
            JOptionPane.showMessageDialog(this, "Plz , Select Your Category....");
            return false;
        }

        return true;
    }

    private void catgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catgActionPerformed
        category1();
    }//GEN-LAST:event_catgActionPerformed

    void faseData(String uname, String pass) {
        pass = pass1.getText();
        uname = username.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");                   // totelamount
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentapp", "root", "pavan@1234");
            PreparedStatement st = con.prepareStatement("SELECT * from homepage WHERE username= ? and password= ? ");
            st.setString(1, uname);
            st.setString(2, pass);
            ResultSet rs = st.executeQuery();
            if (rs.next()) {
                amount = rs.getString(11);//totelamount  11
//JOptionPane.showMessageDialog(this,"Data Selected Success...");
            } else {
                JOptionPane.showMessageDialog(this, "Invalid Username Or Password....");
            }

        } catch (Exception e) {
            // e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Validation Issues....");
        }
    }

    void deleteData(int id1) {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");                   // totelamount
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentapp", "root", "pavan@1234");
            PreparedStatement st = con.prepareStatement("delete from discount WHERE id=?");
            st.setInt(1, id1);
            st.execute();
            JOptionPane.showMessageDialog(this, "Deleted Successfull");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Deleted Not Successfull");
        }

    }

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        idstd.setVisible(false);
        jLabel5.setVisible(false);
        if (validation()) {
            faseData(uname, pass);
            insertData();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void idstdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idstdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idstdActionPerformed
    int id1;

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        idstd.setVisible(true);
        jLabel5.setVisible(true);
        JOptionPane.showMessageDialog(this, "Please , Enter Student Id Only to Delete Data....");
        id1 = Integer.parseInt(idstd.getText());

        deleteData(id1);
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new category().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> catg;
    private javax.swing.JLabel catglbl1;
    private javax.swing.JLabel catglbl2;
    private javax.swing.JButton delete;
    private javax.swing.JTextField idstd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextPane p1;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JLabel perctg;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    private int setInt(int i) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
