/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.student_app;

/**
 *
 * @author Admin
 */
public class Next extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Next.class.getName());

    /**
     * Creates new form Next
     */
    public Next() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t1 = new java.awt.TextArea();
        clear = new java.awt.Button();
        thought = new java.awt.Label();
        back = new java.awt.Button();
        view1 = new java.awt.Button();
        label3 = new java.awt.Label();
        thought1 = new java.awt.Label();
        good = new java.awt.Label();
        view2 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 0));
        setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N

        t1.setBackground(new java.awt.Color(204, 255, 255));
        t1.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        t1.setForeground(new java.awt.Color(0, 204, 0));

        clear.setBackground(new java.awt.Color(255, 255, 51));
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        clear.setForeground(new java.awt.Color(153, 0, 153));
        clear.setLabel("View");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        thought.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        thought.setForeground(new java.awt.Color(255, 0, 153));
        thought.setText("!!!.......THANKS ,  fOR WATCHING UNTIL THE LAST PAGE......!!!");

        back.setBackground(new java.awt.Color(255, 255, 51));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        back.setForeground(new java.awt.Color(102, 0, 102));
        back.setLabel("Go Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        view1.setBackground(new java.awt.Color(255, 255, 51));
        view1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        view1.setForeground(new java.awt.Color(153, 0, 153));
        view1.setLabel("Clear");
        view1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view1ActionPerformed(evt);
            }
        });

        label3.setFont(new java.awt.Font("Georgia", 2, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(204, 0, 102));
        label3.setText("Created By Jadhav Pavan Techno..");

        thought1.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        thought1.setForeground(new java.awt.Color(255, 51, 102));
        thought1.setText("share your thought  , with me....!!!");

        good.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        good.setForeground(new java.awt.Color(255, 0, 153));
        good.setText("Good Bye  ,  Guys.....!!!");

        view2.setBackground(new java.awt.Color(255, 255, 51));
        view2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        view2.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        view2.setForeground(new java.awt.Color(153, 0, 153));
        view2.setLabel("Close");
        view2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Vivaldi", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("Created By Jadhav Pavan techno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(thought, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(thought1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(view1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(good, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(view2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(312, 312, 312)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(313, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(thought, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thought1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(view1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(good, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(view2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(278, 278, 278)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(279, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        t1.setText("      !!          Our project to provided Some Facility..     !!\n\n"+"       Here Some Tips for You ....\n\n"+""
            +"Fees collection is the most tedious \ntask for any educational institution \nand requires precise attention for calculations\n such as pending fees status, fees \nconcessions, scholarships & discounts, \netc. Moreover the manual fees calculations \n& collection process doesn’t guarantee \n100% accuracy. Chances of errors while \nmanaging fees manually are tremendous \nwhich may impact the overall work procedure\n adversely. This is why switching to automated \nfee collection software is a smart decision for\n any institution. It not just delivers accurate\n fees-related calculations but also saves enormous \ntime & effort of the administrative staff.\n" +
            "\n" +
            "A fee management system is used as\n task management software that automates\n collecting fees and generating fee receipts. \nIt eliminates duplicate data entries and \nminimizes errors when entering entries \ninto school accounts. The system supports \nall sizes of public and private institutes.\n" +
            "\n" +
            "Features Of Fees Collection Software\n" +
            "section-heading\n" +
            "1\n" +
            "Simple Registration Process\n" +
            "Institutions just need to enter their \nemail ID & mobile number to get registered \non MasterSoft’s fees collection portal.\n If you have implemented MasterSoft's \nERP software, you can directly transfer the \nentire fees-related data to the cloud. \nIn case you don’t use ERP, there’s a provision \nto upload course & fees details online \nvia Excel.\n" +
            "\n" +
            "2\n" +
            "Precise Fees Calculations\n" +
            "The student fees collection software\n enables the administrative department\n to auto-calculate fees for various categories\n of students considering factors like merit,\n scholarship, concessions, religion, caste, etc.\n" +
            "\n" +
            "3\n" +
            "Multiple Modes Of Fees Payment\n" +
            "Designed & developed with the latest\n framework, the fees manaement system\n offers multiple modes of fees payment such\n as - debit card, credit card, or net banking.\n The fee is processed & transferred to the institution’s\n account within 24 hours as per the norms of GOI.\n" +
            "\n" +
            "4\n" +
            "Role-Based Access To The Staff\n" +
            "The online fees collection portal provides \nrole-based access to the staff members to \nensure complete data security & eliminate\n the risk of data theft in the institution.\n The admin can define access rights based on the \nposition of the staff.\n" +
            "\n" +
            "5\n" +
            "AI-Powered Analytics Dashboard\n" +
            "The fees management system enables \nthe administrative faculty & higher management\n authorities to keep a tab on real-time data \non daily fees transactions & generate fees \ncollection MIS reports.\n" +
            "\n" +
            "6\n" +
            "Fees Notifications & E-Receipts\n" +
            "The online fees payment software sends \nauto-generated pending fees-related reminders & notifications\n to parents every month or at a pre-defined time.\n Also, the fees software generates an e-receipt\n after every successful transaction & sends it to their \nregistered email ID or mobile.\n" +
            "\n" +
            "Online And Offline Fees Collection Software\n" +
            "MasterSoft’s fees collection software \nis a 100% safe and secure platform to deliver \nonline & offline fees collection & other\n fees-related operations seamlessly.\n" +
            "\n" +
            "section-heading\n" +
            "BI Analytics Tools\n" +
            "MasterSoft’s Online Fees Collection Software\n" +
            "Designed and developed on an AI-powered \ntechnological framework, the fees collection software \nsupports multiple modes of fees payment such \nas – debit card, credit card, net banking, \netc. The fees amount can be transferred to the \ninstitution’s bank account online within 24 hours\n as per the norms of the Government of \nIndia with just a few clicks. Student Ledger \nis updated with student fee records & outstanding \nledgers updated.\n" +
            "\n" +
            "Solution\n" +
            "MasterSoft’s Offline - Counter Based Fees Collection\n" +
            "MasterSoft offers the provision of offline- counter-based \nfees collection as well. To make offline payments,\n students can visit the campus and pay the required amount\n of fees on the fees counter. The counter-based \nfees collection software auto-calculates the amount \nthat needs to be paid or outstanding fees. The\n administrative staff just needs to take the \namount and make the entry in the software for records.\n\n\n  "+
                "       Created By jadhav Pavan Techno.."+
                "  \nThanks For To Watching Project Until Last Page....\n\n"
                +"\n     Good Bye , Guys..."+
                " \n\n           Creater Name  :  PAVAN UTTAM JADHAV  "+"\n\n     MCA student at North Maharashtra University(jalgaon)."+"  \n\n           !!........  Thank You  ......!! \n  ");
thought1.setVisible(false);
good.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
        new Homepage().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void view1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view1ActionPerformed
        this.setVisible(true);
        t1.setText("");      
good.setVisible(false);
        thought1.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_view1ActionPerformed

    private void view2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view2ActionPerformed
  this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_view2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Next().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button back;
    private java.awt.Button clear;
    private java.awt.Label good;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label3;
    private java.awt.TextArea t1;
    private java.awt.Label thought;
    private java.awt.Label thought1;
    private java.awt.Button view1;
    private java.awt.Button view2;
    // End of variables declaration//GEN-END:variables
}
