/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.student_app;
import java.time.LocalDateTime;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
//import java.sql.SQLException;
//import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getInt;
//import static javax.swing.UIManager.getString;

/**
 *
 * @author Admin
 */
public class Update extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Update.class.getName());

    /**
     * Creates new form Update
     */
     String s1;
    public Update() {
        initComponents();
        
        var dt=LocalDateTime.now();
        //String s=dt.toString();
        //thought.setText(s);
        DateTimeFormatter dtf; 
        dtf = DateTimeFormatter.ofPattern("  HH:mm:ss");
    s1=dtf.format(dt);    
    thought.setText(s1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clear = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        course = new javax.swing.JTextField();
        updatename = new javax.swing.JButton();
        updatepassword = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        passworderror = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        updatecourse = new javax.swing.JButton();
        back = new javax.swing.JButton();
        clear2 = new javax.swing.JButton();
        usernameerror = new javax.swing.JLabel();
        thought = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        dateOfChange = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        Local_Datatime = new javax.swing.JLabel();

        clear.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        clear.setForeground(new java.awt.Color(153, 0, 153));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setForeground(new java.awt.Color(255, 0, 102));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));
        jPanel4.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(255, 255, 102));
        jLabel3.setFont(new java.awt.Font("Script MT Bold", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Dear Students update Now ,Your Data From Here ...");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(140, 50, 640, 40);

        jLabel4.setBackground(new java.awt.Color(255, 255, 102));
        jLabel4.setFont(new java.awt.Font("SimSun-ExtB", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Creater : Pavan U Jadhav");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(10, 0, 240, 17);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 145, 810, 0);

        jLabel14.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 153));
        jLabel14.setText("How Can Your Thought About Project ?");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(650, 220, 270, 30);

        jLabel11.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 153));
        jLabel11.setText("User Name   : ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 170, 90, 30);

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usernameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });
        getContentPane().add(username);
        username.setBounds(140, 170, 180, 40);

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(140, 270, 180, 40);

        jLabel16.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 153));
        jLabel16.setText("Password  :");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(40, 280, 90, 30);

        course.setBackground(new java.awt.Color(204, 255, 255));
        course.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        course.setForeground(new java.awt.Color(255, 51, 51));
        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });
        course.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                courseKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                courseKeyReleased(evt);
            }
        });
        getContentPane().add(course);
        course.setBounds(670, 140, 210, 40);

        updatename.setBackground(new java.awt.Color(255, 255, 204));
        updatename.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        updatename.setForeground(new java.awt.Color(153, 0, 153));
        updatename.setText("Update Name");
        updatename.setBorder(new javax.swing.border.MatteBorder(null));
        updatename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatenameActionPerformed(evt);
            }
        });
        getContentPane().add(updatename);
        updatename.setBounds(70, 410, 120, 30);

        updatepassword.setBackground(new java.awt.Color(255, 255, 204));
        updatepassword.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        updatepassword.setForeground(new java.awt.Color(153, 0, 153));
        updatepassword.setText(" Update Course");
        updatepassword.setBorder(new javax.swing.border.MatteBorder(null));
        updatepassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatepasswordActionPerformed(evt);
            }
        });
        getContentPane().add(updatepassword);
        updatepassword.setBounds(240, 410, 140, 30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 102));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Enter Date :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 100, 90, 30);

        passworderror.setBackground(new java.awt.Color(255, 255, 102));
        passworderror.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        passworderror.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(passworderror);
        passworderror.setBounds(350, 270, 290, 34);

        jLabel2.setBackground(new java.awt.Color(255, 255, 102));
        jLabel2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Note  :  Please Enter Legal Information Only about students .");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 470, 430, 17);

        jLabel5.setBackground(new java.awt.Color(255, 255, 102));
        jLabel5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("Welcome To Profile Update Page ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 20, 310, 40);

        updatecourse.setBackground(new java.awt.Color(255, 255, 204));
        updatecourse.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        updatecourse.setForeground(new java.awt.Color(153, 0, 153));
        updatecourse.setText("delete ");
        updatecourse.setBorder(new javax.swing.border.MatteBorder(null));
        updatecourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatecourseActionPerformed(evt);
            }
        });
        getContentPane().add(updatecourse);
        updatecourse.setBounds(420, 410, 120, 30);

        back.setBackground(new java.awt.Color(255, 255, 204));
        back.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(153, 0, 153));
        back.setText("GO Back");
        back.setBorder(new javax.swing.border.MatteBorder(null));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(730, 410, 120, 30);

        clear2.setBackground(new java.awt.Color(255, 255, 204));
        clear2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        clear2.setForeground(new java.awt.Color(153, 0, 153));
        clear2.setText("Clear");
        clear2.setBorder(new javax.swing.border.MatteBorder(null));
        clear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear2ActionPerformed(evt);
            }
        });
        getContentPane().add(clear2);
        clear2.setBounds(570, 410, 120, 30);

        usernameerror.setBackground(new java.awt.Color(255, 255, 102));
        usernameerror.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        usernameerror.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(usernameerror);
        usernameerror.setBounds(350, 170, 250, 34);

        thought.setBackground(new java.awt.Color(204, 255, 255));
        thought.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        thought.setForeground(new java.awt.Color(255, 51, 51));
        thought.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoughtActionPerformed(evt);
            }
        });
        thought.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                thoughtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                thoughtKeyReleased(evt);
            }
        });
        getContentPane().add(thought);
        thought.setBounds(660, 260, 250, 40);

        jLabel15.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 0, 153));
        jLabel15.setText("Enter Course Name :");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(700, 100, 140, 30);

        dateOfChange.setMaximumSize(null);
        getContentPane().add(dateOfChange);
        dateOfChange.setBounds(140, 100, 170, 30);

        jLabel6.setBackground(new java.awt.Color(255, 255, 102));
        jLabel6.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("Creater : Pavan U Jadhav");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 0, 170, 20);

        Local_Datatime.setBackground(new java.awt.Color(255, 255, 102));
        Local_Datatime.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        Local_Datatime.setForeground(new java.awt.Color(51, 0, 0));
        getContentPane().add(Local_Datatime);
        Local_Datatime.setBounds(680, 20, 160, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String pass, uname, updatedDate, course1;
    Date d;

    boolean validation() {
        pass = password.getText();
        course1 = course.getText();
        uname = username.getText();
        d = dateOfChange.getDate();
        Local_Datatime.setText(s1);
        
        if (d == null) {
            JOptionPane.showMessageDialog(this, "Please , Enter Todays-Date ");
            return false;
        }
        if (uname.equals("")) {
            JOptionPane.showMessageDialog(this, "Please , Enter Username...");
            return false;
        }
        if (pass.equals("")) {
            JOptionPane.showMessageDialog(this, "Please , Enter Strong Password ... ");
            return false;
        }
        if (course1 == null) {
            JOptionPane.showMessageDialog(this, "Please Enter updated Course");
            return false;
        }

        return true;
    }

    private void changeName(String uname, String pass) throws SQLIntegrityConstraintViolationException {
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentapp", "root", "pavan@1234");
            PreparedStatement ps = con.prepareStatement("UPDATE homepage SET username= ? WHERE password= ?");
            ps.setString(1, uname);//1
            ps.setString(2, pass);//2
            if (ps.execute()) {
                course.setText("Your Name is Update");
                JOptionPane.showMessageDialog(this, "Record Updated SuccessFully..");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Validation Issues..");
        }
    }

    int id = 14;

    public int RollNumber() {

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentapp", "root", "pavan@1234");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT MAX(id) from changecoursename");

            while (rs.next()) {
                id =rs.getInt(1);
                id++;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        return id;
    }

    void updateCourse(String uname, String pass) throws SQLIntegrityConstraintViolationException {

        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            updatedDate = sdf.format(d);
            //uname = username.getText();
            //pass = password.getText();
            course1 = course.getText();
            if(course1.equals(""))
            {
                JOptionPane.showMessageDialog(this,"Please ,  Set New Updated Course Name...");
            }
         
              String sa="update homepage set course = ? where username = ? and password = ?";
              String c1=course.getText();
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentapp", "root", "pavan@1234");
            //PreparedStatement ps = con.prepareStatement("INSERT into changecoursename values(?,?,?,?,?)");
             PreparedStatement ps = con.prepareStatement(sa);
            ps.setString(1, uname);
            ps.setString(2,pass);
            ps.setString(10, c1);
            
         /*
            ps.setInt(1, RollNumber());
            ps.setString(2, uname);
            ps.setString(3, pass);
            ps.setString(4, course1);
            ps.setString(5, updatedDate);
            */
            int x=ps.executeUpdate();
            
            if ( x> 0) {
                JOptionPane.showMessageDialog(this, "Course SuccessFully Updated...");
            
            }/*
         catch (Exception e) {
            JOptionPane.showMessageDialog(this, uname + "  " + " please ,Enter Fill The Information Complately...");
            e.printStackTrace();
                }
            */
            }
         catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Please , Check Information..");
        }
        

    }
    private void usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyPressed
        user();
    }//GEN-LAST:event_usernameKeyPressed

    private void usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyReleased
        user();
    }//GEN-LAST:event_usernameKeyReleased

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed

    }//GEN-LAST:event_passwordActionPerformed
    void passcheck() {
        pass = password.getText();
        if (pass.length() < 8) {
            passworderror.setText("Please Enter Minimum 8 Charector...");
        } else {
            passworderror.setText("");
        }
    }
    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        passcheck();
    }//GEN-LAST:event_passwordKeyPressed

    private void passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyReleased
        passcheck();        // confirmlbl.setText("");
    }//GEN-LAST:event_passwordKeyReleased

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
        passcheck();        // TODO add your handling code here:
    }//GEN-LAST:event_passwordKeyTyped

    private void courseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_courseKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseKeyPressed

    private void courseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_courseKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_courseKeyReleased

    private void updatenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatenameActionPerformed

        if (validation()) {
            uname = username.getText();
            pass = password.getText();
            try {
                changeName(uname, pass);
            } catch (SQLIntegrityConstraintViolationException ex) {
                System.getLogger(Update.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    }//GEN-LAST:event_updatenameActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void updatepasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepasswordActionPerformed

        if (validation()==true) {
            uname = username.getText();
            pass = password.getText();
            try {
                //changePassword(uname,pass);

                updateCourse(uname, pass);
            } catch (SQLIntegrityConstraintViolationException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Validation Issues....");
                //System.getLogger(Update.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    }//GEN-LAST:event_updatepasswordActionPerformed
    void deleteData() {
        uname = username.getText();
        pass = password.getText();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentapp", "root", "pavan@1234");
            PreparedStatement ps = con.prepareStatement("DELETE from hchangecoursename WHERE username = ? and password = ? ");
            ps.setString(1, uname);
            ps.setString(2, pass);
            int i = ps.executeUpdate();
            course.setText("Record Deleted");
            if (i > 0) {
                JOptionPane.showMessageDialog(this, "Record Deleted Successfully...");
            } else {
                JOptionPane.showMessageDialog(this, "Wrong Username Or Password");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void exitActionPerfoaddressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
//this.setVisible(false);  
//new Homepage().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void updatecourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatecourseActionPerformed
        if (validation())
            deleteData();
    }//GEN-LAST:event_updatecourseActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
        new Homepage().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void clear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear2ActionPerformed
        passworderror.setText("");
        usernameerror.setText("");
        password.setText("");
        course.setText("");
        username.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_clear2ActionPerformed
    void user() {
        uname = username.getText();
        if (uname.length() < 10) {
            usernameerror.setText("Enter valid Username");
        } else {
            usernameerror.setText("");
        }
    }
    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
//user();        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped
        user();        // TODO add your handling code here:
    }//GEN-LAST:event_usernameKeyTyped

    private void thoughtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_thoughtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_thoughtKeyPressed

    private void thoughtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_thoughtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_thoughtKeyReleased

    private void thoughtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoughtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thoughtActionPerformed

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Update().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Local_Datatime;
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JButton clear2;
    private javax.swing.JTextField course;
    private com.toedter.calendar.JDateChooser dateOfChange;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passworderror;
    private javax.swing.JTextField thought;
    private javax.swing.JButton updatecourse;
    private javax.swing.JButton updatename;
    private javax.swing.JButton updatepassword;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernameerror;
    // End of variables declaration//GEN-END:variables
}
